'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace RegistroLoginWS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="RegistroLoginWS.RegistroLoginSoap")>  _
    Public Interface RegistroLoginSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/registros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function registros(ByVal pUser As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/registros", ReplyAction:="*")>  _
        Function registrosAsync(ByVal pUser As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface RegistroLoginSoapChannel
        Inherits RegistroLoginWS.RegistroLoginSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RegistroLoginSoapClient
        Inherits System.ServiceModel.ClientBase(Of RegistroLoginWS.RegistroLoginSoap)
        Implements RegistroLoginWS.RegistroLoginSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function registros(ByVal pUser As String) As System.Data.DataTable Implements RegistroLoginWS.RegistroLoginSoap.registros
            Return MyBase.Channel.registros(pUser)
        End Function
        
        Public Function registrosAsync(ByVal pUser As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements RegistroLoginWS.RegistroLoginSoap.registrosAsync
            Return MyBase.Channel.registrosAsync(pUser)
        End Function
    End Class
End Namespace
