'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference3
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference3.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pAsignatura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DedicacionMadia", ReplyAction:="*")>  _
        Function DedicacionMadia(ByVal request As ServiceReference3.DedicacionMadiaRequest) As ServiceReference3.DedicacionMadiaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DedicacionMadia", ReplyAction:="*")>  _
        Function DedicacionMadiaAsync(ByVal request As ServiceReference3.DedicacionMadiaRequest) As System.Threading.Tasks.Task(Of ServiceReference3.DedicacionMadiaResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DedicacionMadiaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DedicacionMadia", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference3.DedicacionMadiaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference3.DedicacionMadiaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DedicacionMadiaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pAsignatura As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pAsignatura As String)
            MyBase.New
            Me.pAsignatura = pAsignatura
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DedicacionMadiaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DedicacionMadiaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference3.DedicacionMadiaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference3.DedicacionMadiaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DedicacionMadiaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public DedicacionMadiaResult As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DedicacionMadiaResult As Double)
            MyBase.New
            Me.DedicacionMadiaResult = DedicacionMadiaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference3.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference3.WebService1Soap)
        Implements ServiceReference3.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference3_WebService1Soap_DedicacionMadia(ByVal request As ServiceReference3.DedicacionMadiaRequest) As ServiceReference3.DedicacionMadiaResponse Implements ServiceReference3.WebService1Soap.DedicacionMadia
            Return MyBase.Channel.DedicacionMadia(request)
        End Function
        
        Public Function DedicacionMadia(ByVal pAsignatura As String) As Double
            Dim inValue As ServiceReference3.DedicacionMadiaRequest = New ServiceReference3.DedicacionMadiaRequest()
            inValue.Body = New ServiceReference3.DedicacionMadiaRequestBody()
            inValue.Body.pAsignatura = pAsignatura
            Dim retVal As ServiceReference3.DedicacionMadiaResponse = CType(Me,ServiceReference3.WebService1Soap).DedicacionMadia(inValue)
            Return retVal.Body.DedicacionMadiaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference3_WebService1Soap_DedicacionMadiaAsync(ByVal request As ServiceReference3.DedicacionMadiaRequest) As System.Threading.Tasks.Task(Of ServiceReference3.DedicacionMadiaResponse) Implements ServiceReference3.WebService1Soap.DedicacionMadiaAsync
            Return MyBase.Channel.DedicacionMadiaAsync(request)
        End Function
        
        Public Function DedicacionMadiaAsync(ByVal pAsignatura As String) As System.Threading.Tasks.Task(Of ServiceReference3.DedicacionMadiaResponse)
            Dim inValue As ServiceReference3.DedicacionMadiaRequest = New ServiceReference3.DedicacionMadiaRequest()
            inValue.Body = New ServiceReference3.DedicacionMadiaRequestBody()
            inValue.Body.pAsignatura = pAsignatura
            Return CType(Me,ServiceReference3.WebService1Soap).DedicacionMadiaAsync(inValue)
        End Function
    End Class
End Namespace
